import type { SoundAsset } from "@/lib/sound-types";

export const click002Sound: SoundAsset = {
  name: "click-002",
  dataUri: "data:audio/mpeg;base64,SUQzBAAAAAAAIlRTU0UAAAAOAAADTGF2ZjYyLjMuMTAwAAAAAAAAAAAAAAD/+1DAAAAAAAAAAAAAAAAAAAAAAABJbmZvAAAADwAAAAIAAAJxAKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqr//////////////////////////////////////////////////////////////////wAAAABMYXZjNjIuMTEAAAAAAAAAAAAAAAAkBMAAAAAAAAACcTXlOTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//tQxAAAChRbWTSXgAF9marDMUAAAWAAAqvBMVitHOe/N3wUQIMRoYyVT5zmmo4RyCbibibibibibi5kLLmXA0DQQxDFYrHkQHwfB8P1Ag75fznL+GOX93T7uXB/Jgg7AZ/hjp9wNUW6SscFrNEjcCSrleHLRZwETeWJZYhZaAcALpqtgM20AwRELtMjZaRkdAXCBZKFooN1VJPQ4pISkIWIaLl/8XKTRFiBGJFf/yKmReLxiXS7//pJGQlCQNf8ShIGip1YICgMYC4zbPq12P/7UsQFg8hoUxgdgwAAAAA0gAAABK3OZdxxx5j5oBCUWpzQUGAQCCkt/5wMAgpKDTjxUFTuDQNTywVOlZYGuCp3UDXEruHeVdyPW7s61UxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
  duration: 0.012,
  format: "mp3",
  license: "CC0",
  author: "Kenney",
};
