import type { SoundAsset } from "@/lib/sound-types";

export const click005Sound: SoundAsset = {
  name: "click-005",
  dataUri: "data:audio/mpeg;base64,SUQzBAAAAAAAIlRTU0UAAAAOAAADTGF2ZjYyLjMuMTAwAAAAAAAAAAAAAAD/+1DAAAAAAAAAAAAAAAAAAAAAAABJbmZvAAAADwAAAAIAAAJxAKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqr//////////////////////////////////////////////////////////////////wAAAABMYXZjNjIuMTEAAAAAAAAAAAAAAAAkBYYAAAAAAAACcVthG6QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//tQxAAACVg/VjTzAAGTIWyzMNAAAQuCwf4t4R8JGLmly+A5wkZC1XZ48eU/9nkydwDgMmTPgg7B+JwfB94jD+sMFwfD5cP6wQg+Hy4P6wQOLD9/hiJzX+JHfyhz+UBAAABESAkWjyhiRAAG1QoiU9/hlk9qWt/kypbl3/JQFNcvYhi6JcpkeIGSQug3EDZRJeF5FwbzapJVvoDhNB5GXdH/WdNSclXWzf/JUqNUqRNMNL//l1VSzxiGU//BV1oSiZv/+UUhJOSVgICCoKjAVP/7UsQFg8ZQBvZ8MIAAAAA0gAAABOg0PDcSxFDsq5HLHl+e+z4a4i63FutyvO8RQ7xL/9dZ1R4s+SWGuRVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
  duration: 0.007,
  format: "mp3",
  license: "CC0",
  author: "Kenney",
};
